# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwaziMvp',
            fields=[
                ('id', models.TextField(db_column='id', primary_key=True, serialize=False)),
                ('country_name', models.TextField(blank=True, db_column='country_name', null=True)),
                ('water_source', models.TextField(blank=True, db_column='water_source', null=True)),
                ('water_tech', models.TextField(blank=True, db_column='water_tech', null=True)),
                ('status_id', models.TextField(blank=True, db_column='status_id', null=True)),
                ('install_year', models.TextField(blank=True, db_column='install_year', null=True)),
                ('lat_deg', models.TextField(blank=True, db_column='lat_deg', null=True)),
                ('lon_deg', models.TextField(blank=True, db_column='lon_deg', null=True)),
                ('fuzzy_water_source', models.TextField(blank=True, db_column='fuzzy_water_source', null=True)),
                ('predicted_class', models.TextField(blank=True, db_column='predicted_class', null=True)),
                ('probability', models.TextField(blank=True, db_column='probability', null=True)),
                ('one_km_population', models.TextField(blank=True, db_column='one_km_population', null=True)),
                ('one_km_total_water_points', models.TextField(blank=True, db_column='one_km_total_water_points', null=True)),
                ('one_km_functioning_water_points', models.TextField(blank=True, db_column='one_km_functioning_water_points', null=True)),
            ],
        ),
    ]
