# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watermap', '0002_swazimvp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swazimvp',
            options={'managed': False},
        ),
    ]
