# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watermap', '0003_auto_20180312_0215'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='swazimvp',
            table='swazi_mvp',
        ),
    ]
